// src/views/TotalChart.vue
<template>
    <v-chart class="chart" :option="option" />
</template>

<script>
    import {use} from 'echarts/core'
    import {
        TooltipComponent,
        GridComponent,
        LegendComponent,
        MarkLineComponent,
    } from 'echarts/components'
    import {BarChart} from 'echarts/charts'
    import {CanvasRenderer} from 'echarts/renderers'

    import VChart from 'vue-echarts'
    import {ref, defineComponent} from 'vue'
    import global from '../../src/components/GlobalData'

    use([
        TooltipComponent,
        GridComponent,
        LegendComponent,
        MarkLineComponent,
        BarChart,
        CanvasRenderer,
    ])

    export default defineComponent({
        name: 'HelloWorld',
        components: {
            VChart,
        },
        setup() {
            const waterStack = {
                name: '水',
                type: 'bar',
                stack: 'Ad',
                data: global.waterData,
                itemStyle: {normal: {label: {show: true}, color: '#73c0de'}},
            }
            const electricityStack = {
                name: '电',
                type: 'bar',
                stack: 'Ad',
                emphasis: {
                    focus: 'series',
                },
                data: global.electricityData,
                itemStyle: {normal: {label: {show: true}, color: '#fac858'}},
            }
            const gasStack = {
                name: '气',
                type: 'bar',
                stack: 'Ad',
                emphasis: {
                    focus: 'series',
                },
                data: global.gasData,
                itemStyle: {normal: {label: {show: true}, color: '#91cc75'}},
            }
            let mySeries = [waterStack, electricityStack, gasStack]
            let totalData = []
            for (let i = 0; i < waterStack.data.length; i++) {
                totalData.push(
                    waterStack.data[i] +
                        electricityStack.data[i] +
                        gasStack.data[i]
                )
            }
            const totalStack = {
                name: '',
                stack: 'Ad2',
                type: 'bar',
                barGap: '-100%',
                data: totalData,
                itemStyle: {
                    normal: {
                        label: {
                            show: true,
                            position: 'top',
                        },
                        color: 'rgba(128, 128, 128, 0)',
                    },
                },
            }
            mySeries.push(totalStack)
            let option = ref({
                darkMode: 'auto',
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'shadow',
                    },
                },
                legend: {},
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true,
                },
                xAxis: [
                    {
                        type: 'category',
                        data: global.monthRange,
                    },
                ],
                yAxis: [
                    {
                        type: 'value',
                    },
                ],
                series: mySeries,
            })
            return {option}
        },
    })
</script>

<style scoped>
    .chart {
        height: 500px;
    }
</style>

// src/pages/TotalChart.tsx
import { useMemo } from 'react'
import FeeChart from '../components/FeeChart'
import { useFeeData } from '../hooks/useFeeData'
import { feeColors, feeLabels } from '../services/api'
import type { EChartsOption } from 'echarts'
import './ChartPage.css'

export default function TotalChart() {
    const { data, loading, error } = useFeeData()

    const charts = useMemo(() => {
        const currentYear = new Date().getFullYear()
        const years: number[] = []

        for (let year = currentYear; year >= 2021; year--) {
            years.push(year)
        }

        return years.map(year => {
            const waterData = data.water[year] || Array(12).fill(0)
            const electricityData = data.electricity[year] || Array(12).fill(0)
            const gasData = data.gas[year] || Array(12).fill(0)

            const totalData = waterData.map((_, i) =>
                waterData[i] + electricityData[i] + gasData[i]
            )
            const yearTotal = totalData.reduce((a, b) => a + b, 0)

            const option: EChartsOption = {
                tooltip: {
                    trigger: 'axis',
                    axisPointer: { type: 'shadow' },
                    backgroundColor: 'rgba(20, 25, 35, 0.95)',
                    borderColor: 'rgba(255, 255, 255, 0.1)',
                    textStyle: { color: '#fff' },
                },
                legend: {
                    data: ['水', '电', '气'],
                    textStyle: { color: '#a0a0a0' },
                },
                xAxis: {
                    type: 'category',
                    data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
                    axisLine: { lineStyle: { color: '#444' } },
                    axisLabel: { color: '#888' },
                },
                yAxis: {
                    type: 'value',
                    axisLine: { lineStyle: { color: '#444' } },
                    axisLabel: { color: '#888' },
                    splitLine: { lineStyle: { color: '#333' } },
                },
                series: [
                    {
                        name: feeLabels.water,
                        type: 'bar',
                        stack: 'total',
                        emphasis: { focus: 'series' },
                        data: waterData,
                        itemStyle: { color: feeColors.water.main },
                        label: {
                            show: true,
                            color: '#000',
                            fontSize: 10,
                            formatter: (p) => p.value && Number(p.value) > 0 ? String(p.value) : '',
                        },
                    },
                    {
                        name: feeLabels.electricity,
                        type: 'bar',
                        stack: 'total',
                        emphasis: { focus: 'series' },
                        data: electricityData,
                        itemStyle: { color: feeColors.electricity.main },
                        label: {
                            show: true,
                            color: '#000',
                            fontSize: 10,
                            formatter: (p) => p.value && Number(p.value) > 0 ? String(p.value) : '',
                        },
                    },
                    {
                        name: feeLabels.gas,
                        type: 'bar',
                        stack: 'total',
                        emphasis: { focus: 'series' },
                        data: gasData,
                        itemStyle: { color: feeColors.gas.main },
                        label: {
                            show: true,
                            color: '#000',
                            fontSize: 10,
                            formatter: (p) => p.value && Number(p.value) > 0 ? String(p.value) : '',
                        },
                    },
                    {
                        name: '',
                        type: 'bar',
                        stack: 'overlay',
                        barGap: '-100%',
                        data: totalData,
                        itemStyle: { color: 'transparent' },
                        label: {
                            show: true,
                            position: 'top',
                            color: feeColors.total.main,
                            fontWeight: 'bold',
                            formatter: (p) => p.value && Number(p.value) > 0 ? `$${p.value}` : '',
                        },
                    },
                ],
            }

            return { year, option, total: yearTotal }
        })
    }, [data])

    if (loading) {
        return (
            <div className="chart-page">
                <h1 className="page-title">费用总览</h1>
                <div className="loading-container">
                    <div className="loading-spinner" />
                    <p>加载中...</p>
                </div>
            </div>
        )
    }

    if (error) {
        return (
            <div className="chart-page">
                <h1 className="page-title">费用总览</h1>
                <div className="error-container">
                    <p>加载失败: {error.message}</p>
                </div>
            </div>
        )
    }

    return (
        <div className="chart-page">
            <h1 className="page-title">
                <span className="title-icon">📊</span>
                费用总览
            </h1>
            {charts.map(({ year, option, total }) => (
                <FeeChart
                    key={year}
                    option={option}
                    title={String(year)}
                    subtitle={`$${total.toFixed(0)}`}
                />
            ))}
        </div>
    )
}
